import { Inter } from 'next/font/google'
import { Splide, SplideSlide } from '@splidejs/react-splide';
import '@splidejs/react-splide/css/skyblue';
import '@splidejs/react-splide/css/sea-green';
import Navbar from '@/components/Navbar';
import Xarrow, { Xwrapper } from "react-xarrows";
import Link from 'next/link';
import Image from 'next/image';
import Post from '@/components/Post';
import { comunidades, posts } from '@/components/assets';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import { FavoritsOnRight } from '@/components/FavoritsOnRight';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [havBests, setHaveBests] = useState<boolean>(false)
  const [favoritListID, setFavoritListID] = useState<string[]>([])
  useEffect(() => {
    const favorites = localStorage.getItem('favoritos');
    if (favorites) {
      if (JSON.parse(favorites).length < 1 || favorites.includes("post_") === false) {
        setHaveBests(false)
      } if (JSON.parse(favorites).length > 0 && favorites.includes("post_")) {
        setHaveBests(true)
      }
      setFavoritListID(JSON.parse(favorites))
    }
  })

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen flex flex-col items-center overflow-x-hidden">
        <div className='min-[1600px]:w-[1600px] flex flex-col items-center'>
          <div className='w-full' id='bests'>
            <Splide
              options={{
                rewind: true,
                gap: '1rem',
                autoplay: true,
                type: 'loop',
                pauseOnHover: false,
                resetProgress: false,
                height: '24rem',
                interval: 4000,
                speed: 1000,
                easing: 'ease'
              }}
              aria-label="Bests"
            >
              {posts.map((best, index) => best.isbest == true ? (
                <SplideSlide key={index}>
                  <div className='h-96 relative w-full' onClick={() => console.log("ola")}>
                    <img src={best.url_da_image} className='w-full h-full object-cover' alt="" />
                    <div className='absolute z-10 bottom-3 left-3 w-[350px] h-fit min-h-[144px] bg-black/20 p-5'>
                      <h1 className={`${inter.className} text-white capitalize text-3xl font-semibold mb-2 break-words`}>
                        {best.nome != null
                          ? best.nome.length > 30
                            ? best.nome.slice(0, 30) + "..."
                            : best.nome
                          : ""}</h1>
                      <p className='text-white capitalize text-sm leading-5 break-words'>{best.descricao != null
                        ? best.descricao.length > 130
                          ? best.descricao.slice(0, 130) + "..."
                          : best.descricao
                        : ""}</p>
                    </div>

                  </div>
                </SplideSlide>
              ) : "")}
            </Splide>
          </div>
          <div className='flex flex-col justify-center items-center w-[80%] h-fit'>
            <div className='w-[60%] flex justify-between items-center'>
              {comunidades.map((comp, index) => (
                <div title={comp.name} key={`profile${index}`} id={`satrt${index}`} className='cursor-pointer w-[50px] h-[50px] rounded-full overflow-hidden bg-white '>
                  <Image src={`${comp.image}`} alt='d' width={500} height={500} className='object-cover w-full h-full' />
                  <Xarrow start={`satrt${index}`} end={`name${index}`} startAnchor={'bottom'} headSize={0} strokeWidth={1} endAnchor={'top'} color={comp.color} path='grid' curveness={1} dashness={{ nonStrokeLen: 3, strokeLen: 3 }} />
                </div>
              ))}
            </div>
            <div className='w-full flex justify-between items-center mt-6'>
              {comunidades.map((comp, index) => (
                <div key={`name${index}`} id={`name${index}`} className={`text-white px-3 w-[145px] text-center py-[2px] rounded`} style={{ backgroundColor: comp.color }}>{comp.name}</div>
              ))}
            </div>
          </div>
          <div className={`relative  my-6 w-full px-8 h-fit flex justify-between items-start`}>
            <div className={`bg-[#00000083] border-2 border-black ${havBests ? "w-[75%] duration-150 grid-cols-4" : "w-full grid-cols-5 duration-150"} h-fit grid  pt-4`}>
              {posts.map((post) => (
                <Post key={post.id} data={post} />
              ))}

            </div>
            {
              havBests && (<div className='bg-[#00000083] w-[23%] h-fit p-2 border-2 border-black'>
                {posts
                  .filter((post) => favoritListID.includes(post.id))
                  .map((post) => (
                    <FavoritsOnRight key={post.id} post={post} />
                  ))}
              </div>)
            }
          </div>
        </div>
      </main>
    </>
  )
}

